sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t msclin/aws-docker-react .

script:
  - docker run -e CI=true msclin/aws-docker-react npm run test -- --coverage